// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_tabel.Services.TimeShiftContext;

#nullable disable

namespace web_tabel.Services.Migrations
{
    [DbContext(typeof(TimeShiftDBContext))]
    partial class TimeShiftDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web_tabel.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("web_tabel.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeOfEmploymentName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("WorkScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StaffScheduleId");

                    b.HasIndex("TypeOfEmploymentName");

                    b.HasIndex("WorkScheduleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("web_tabel.Domain.EmployeeCondition", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TypeOfWorkingTimeName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.HasIndex("TypeOfWorkingTimeName");

                    b.ToTable("EmployeeCondition");
                });

            modelBuilder.Entity("web_tabel.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("web_tabel.Domain.StaffSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("NumberOfPositions")
                        .HasColumnType("real");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("WorkScheduleId");

                    b.ToTable("StaffSchedules");
                });

            modelBuilder.Entity("web_tabel.Domain.TimeShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("HoursPlanned")
                        .HasColumnType("real");

                    b.Property<float>("HoursWorked")
                        .HasColumnType("real");

                    b.Property<Guid>("TimeShiftPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeEmploymentPlannedName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TypeEmploymentWorkedName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TimeShiftPeriodId");

                    b.HasIndex("TypeEmploymentPlannedName");

                    b.HasIndex("TypeEmploymentWorkedName");

                    b.HasIndex("WorkScheduleId");

                    b.ToTable("TimeShifts");
                });

            modelBuilder.Entity("web_tabel.Domain.TimeShiftPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Closed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TimeShiftPeriods");
                });

            modelBuilder.Entity("web_tabel.Domain.TypeOfEmployment", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("TypeOfEmployments");
                });

            modelBuilder.Entity("web_tabel.Domain.TypeOfWorkingTime", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ColorText")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("TypeEmployments");
                });

            modelBuilder.Entity("web_tabel.Domain.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("HoursInWeek")
                        .HasColumnType("real");

                    b.Property<bool>("IsWeekly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReferenceDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("web_tabel.Domain.WorkingCalendar", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Date");

                    b.HasIndex(new[] { "Year" }, "IX_WorkingCalendar_Year");

                    b.ToTable("WorkingCalendar");
                });

            modelBuilder.Entity("web_tabel.Domain.Department", b =>
                {
                    b.HasOne("web_tabel.Domain.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("web_tabel.Domain.Employee", b =>
                {
                    b.HasOne("web_tabel.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_tabel.Domain.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("web_tabel.Domain.StaffSchedule", "StaffSchedule")
                        .WithMany()
                        .HasForeignKey("StaffScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("web_tabel.Domain.TypeOfEmployment", "TypeOfEmployment")
                        .WithMany()
                        .HasForeignKey("TypeOfEmploymentName");

                    b.HasOne("web_tabel.Domain.WorkSchedule", "WorkSchedule")
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("web_tabel.Domain.EmployeeName", "Name", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("EmployeeNames");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Department");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("StaffSchedule");

                    b.Navigation("TypeOfEmployment");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("web_tabel.Domain.EmployeeCondition", b =>
                {
                    b.HasOne("web_tabel.Domain.TypeOfWorkingTime", "TypeOfWorkingTime")
                        .WithMany()
                        .HasForeignKey("TypeOfWorkingTimeName");

                    b.Navigation("TypeOfWorkingTime");
                });

            modelBuilder.Entity("web_tabel.Domain.StaffSchedule", b =>
                {
                    b.HasOne("web_tabel.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_tabel.Domain.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("web_tabel.Domain.WorkSchedule", "WorkSchedule")
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Organization");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("web_tabel.Domain.TimeShift", b =>
                {
                    b.HasOne("web_tabel.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_tabel.Domain.TimeShiftPeriod", "TimeShiftPeriod")
                        .WithMany()
                        .HasForeignKey("TimeShiftPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_tabel.Domain.TypeOfWorkingTime", "TypeEmploymentPlanned")
                        .WithMany()
                        .HasForeignKey("TypeEmploymentPlannedName");

                    b.HasOne("web_tabel.Domain.TypeOfWorkingTime", "TypeEmploymentWorked")
                        .WithMany()
                        .HasForeignKey("TypeEmploymentWorkedName");

                    b.HasOne("web_tabel.Domain.WorkSchedule", "WorkSchedule")
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TimeShiftPeriod");

                    b.Navigation("TypeEmploymentPlanned");

                    b.Navigation("TypeEmploymentWorked");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("web_tabel.Domain.WorkSchedule", b =>
                {
                    b.OwnsMany("web_tabel.Domain.WorkSchedulleHours", "HoursByDayNumbers", b1 =>
                        {
                            b1.Property<Guid>("WorkScheduleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DayNumber")
                                .HasColumnType("int");

                            b1.Property<string>("TypeOfWorkingTimeName")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<float>("Hours")
                                .HasColumnType("real");

                            b1.HasKey("WorkScheduleId", "DayNumber", "TypeOfWorkingTimeName");

                            b1.HasIndex("TypeOfWorkingTimeName");

                            b1.ToTable("WorkSchedulleHours");

                            b1.HasOne("web_tabel.Domain.TypeOfWorkingTime", "TypeOfWorkingTime")
                                .WithMany()
                                .HasForeignKey("TypeOfWorkingTimeName")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("WorkScheduleId");

                            b1.Navigation("TypeOfWorkingTime");
                        });

                    b.Navigation("HoursByDayNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
